# Generated by Django 4.2.7 on 2025-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='submissions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
